# Generated by Django 5.0.3 on 2024-03-13 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='manufactured_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата производства продукта'),
            preserve_default=False,
        ),
    ]
